lib/index.js
package.json

This PR will allow setting debug logs on through opts.
```
var PubSub = require('appc-pubsub'),
pubsub = new PubSub({
key: 'MY_KEY',
secret: 'MY_SECRET',
debug: true
});
```

Allow setting debug through opts

---

lib/index.js
package.json

This PR adds cloning of the data object in pubsub.publish.  Since objects are inherently pass by ref, the scrubbing that takes places on a user doc (and presumably others) is causing password and password_salt to get set to "[HIDDEN]" in preprod when a user logs in since the serialization pass is modifying the doc.
```
data:PRIMARY> db.users.find({ password: /HIDDEN/ }).count()
67
```

Fix case where user objects are being modified prior to save

---

lib/index.js
package.json

This PR...
- introduces support for a opts flag (`exitOnError`) to control whether the client should fire a process.exit when an unrecoverable error occurs as a result of an uncaughtException handling unexpected codes from web response (defaulted to `false`)
- handle two specific error codes seen crashing 360 in the past day or so
- fixes opts handling for env/url to prefer values passed in rather than the known envs (it was just missing the parens on the fallback, seeing `opts.env || isRunningInPreproduction()` as truthy for any `opts.env` value passed in)

Add opts flag for exit behavior, handle ECONNRESET/ESOCKETTIMEDOUT codes, bump to 0.0.34

---

lib/index.js
package.json

This PR mitigates uncaught exceptions caused by cert hostname/IP mismatches seen in pre-production environments by only forcing rejection in production.  It also fixes an npm warning by switching to the preferred SPDX "SEE LICENSE IN..." expression.

[PUBSUB-6] Only reject cert hostname mismatches in production environments

---

lib/index.js

https://jira.appcelerator.org/browse/PUBSUB-8
This PR cleans up the error handling, so that when errors occur during an event publish, that event will get re-queued instead of only when specific connection errors occur. 
In the case that the event is in a closing state when an error occurs, the error will be logged, but the event will not get re-queued.

[PUBSUB-8] Uncaught exception in client on hostname/ip mismatch

---

lib/index.js
package.json

https://jira.appcelerator.org/browse/PUBSUB-9
This PR wraps newrelic calls in a try/catch since they have a habit of throwing exceptions and we want to handle them as early as possible. The error is then emitted by pubsub for further handling.

[PUBSUB-9] Uncaught exceptions from newrelic cause process to crash

---

lib/index.js
package.json

https://jira.appcelerator.org/browse/PUBSUB-10
This PR logs error status code and response body rather than emitting them, so they don't go uncaught and crash the parent process.  Errors during instancing or initial connection still email and `Unauthorized` still emits and fires closeAfterFire.

[PUBSUB-10] emit unauthorized resp, but consume and log errors

---

lib/index.js
package.json

https://jira.appcelerator.org/browse/PUBSUB-13
The pubsub client is using socket.io's namespaced events. Changing the name should fix any unexpected ping/pong issues.

[PUBSUB-13] change ping/pong

---

lib/index.js
package.json

Jira: https://jira.appcelerator.org/browse/PUBSUB-12
This PR attempts to force reconnection. Socket.io default reconnection is as follows:
```
reconnect: true,
reconnectionAttempts: Infinity,
reconnectionDelay: 1000,
reconnectionDelayMax: 5000,
timeout: 20000
```
This PR does not modify the default behavior, However which leads me to believe that the underline issue maybe something different. This PR will force reconnect if the server closes the connection (default behavior if the socket doesn't pong back within X seconds)

[PUBSUB-12] force reconnect

---

lib/index.js
package.json

Jira: https://jira.appcelerator.org/browse/PUBSUB-17
This PR will add events for the socket connection in which the consumers can handle socket states
0. edit etc/hosts file and add `pubsub-local.cloud.appctest.com`
1. In pubsub server, edit app.js look for the code `!found[key]` and make sure `removeClientWithUUID(key);` is always called by removing the if statement.
2. Run pubsub server locally
3. Run webevent server locally (update config to point to local pubsub server `https://pubsub-local.cloud.appctest.com:8443` in `conf/pubsub.development.js`)
4. Pubsub will terminate the socket connection after about ~10 secs. At this point pubsub client in webevent will reconnect to pubsub-server.
5. Open a browser tab to pubsub-server arrow admin …

[PUBSUB-17] add socket connection events

---

lib/index.js

Jira: https://jira.appcelerator.org/browse/PUBSUB-17
This PR changes the behavior when the server disconnects the client, the client no longer will removeAllListeners, resolving the issue in which the client would reconnect but would no longer emit to the consumer.
Node docs warns about bad practices with the usage: https://nodejs.org/api/events.html#events_emitter_removealllisteners_eventname
0. edit etc/hosts file and add `pubsub-local.cloud.appctest.com`
1. In pubsub server, edit app.js look for the code `!found[key]` and make sure `removeClientWithUUID(key);` is always called by removing the if statement.
2. Run pubsub server locally
3. Run webevent server locally (update config to point to local pubsub server `https://pubsub-local.cloud.appctest.com:8443` in …

[PUBSUB-17] remove removeAllListeners

---

lib/index.js
package.json
test/_helper.js
test/webhook.js

https://techweb.axway.com/jira/browse/PUBSUB-51
This PR adds two methods to the pubsub client:
- `authenticateWebhook(req, res, next)`
This function authenticates that a request has come from pubsub server, using the clients configured authentication method. The parameters `res` and `next` are optional for use as middleware, where it will send a 401 response for unauthorized requests.
- `handleWebhook(req, res)`
A route handler that will run authentication and wire up events to be listened to using the EventEmitter pattern.
The functions must be called after the request body has been parsed.
The client config has to be fetched from the server when the client is started, and a `configured` event is emitted once that's done.
The clients topic list will be checked when adding a listener, and …

[PUBSUB-51] Add consumer helper methods

---

lib/index.js
package.json

This PR will remove confusing use of debug when the opts passed to pubsub contain a `debug:true` flag, the client overrides debug and logs to console using `colors` module
No functionality is lost as the common way to get debug logs is to specify: `DEBUG=appc:pubsub`

remove debug override and colors module

---

lib/index.js

This PR will correct an issue retrieving the fingerprint on `darwin` machines which was causing the fingerprinting to run over and over causing CPU churn on every published event.
I changed it to make better use of `ioreg` and `awk` in order to complete in two commands, rather than six, so it's much more efficient in the first place.

Correct and optimize darwin fingerprint retrieval

---

lib/index.js
package.json
test/webhook.js

https://techweb.axway.com/jira/browse/PUBSUB-76
Another go-round on matching wildcard subscribed topics.  Same check will be applied server-side to bust out duplicate emitted events when subscribing on descendant event namespaces.

[PUBSUB-76] redux on pattern matching, bump version to 1.1.2

---

.travis.yml
lib/index.js
package.json
test/validation.js
test/webhook.js

Two key changes here...
1. We no longer emit based on matching the event to the client's subscribed topics.  appc-pubsub-server will post a topic in the payload sent to the webhook and will now emit that topic exactly if it's configured as subscribed.
1. The validation helper method is now a "public" property on am instanced client.  The server will use a disabled client's subscribed topic logic to validate what clients should receive a published event. (I.e., let's not duplicate this logic.)
Any project currently using a 1.X client should upgrade to 1.2.0 once published.

[PUBSUB-76] Only emit events for the posted topic, improved validation on event receipt

---

lib/index.js
package.json
test/validation.js

https://techweb.axway.com/jira/browse/PUBSUB-80
Minor change from 1.2.0...
The `isSubscribedTopic` function was refactored to `getSubscribedTopic` which returns the first matching subscribed topic for a given client (or null), rather than a boolean if the topic was found.
Also added validation tests for cases where the topic list is passed in.
This bumps to a 1.3.0, but there's no functional changes for existing clients.

[PUBSUB-80] Get subscribed topic

---

lib/index.js
package-lock.json
package.json
test/validation.js
test/webhook.js

This PR updates dependencies and sets latest maintenance LTS 12.X as min node version.

1.5.0 - Update dependencies, set node 12 as min version

---

lib/index.js
package-lock.json
package.json

https://jira.axway.com/browse/PUBSUB-335
This PR introduces a minor behavior change to default the timestamp in the `options` argument of published events if not passed in the `client.publish` call's options. With debug enabled, the log entry for the `_send` call will now show the defaulted timestamp in options.
```
appc:pubsub _send my.awesome.event-1645762322518 {
data: { some_prop: true, ... },
event: 'my.awesome.event',
options: { timestamp: 1645762322518 }
} 
```

1.7.0 - [PUBSUB-335] Default timestamp on publish if not passed in options

---

LICENSE
package-lock.json
package.json

https://jira.axway.com/browse/PUBSUB-355
This PR changes pubsub client from old Appcelerator commercial license to Apache 2.0 to make mend.io happy. 😸 And since @ingo says it doesn't require a major, it's not. 👍
Once this publishes, all versions < 1.8.0 will be marked as deprecated.

1.8.0 - Change from commercial to Apache 2.0 license

---

lib/index.js
test/_helper.js
test/webhook.js

https://jira.axway.com/browse/PUBSUB-382
Before https://github.com/appcelerator/appc-pubsub/pull/49 authenticateWebhook and handleWebhook were synchronous and authenticateWebhook would return true/false. With the body parsing they are both asynchronous now so the true/false value can be returned without affecting use as a middleware.
Are the tests happy again, and can you receive events as expected. Particularly when the client does it's own body parsing.

[PUBSUB-382] Make webhook functions async

---

package-lock.json
package.json

This PR updates following dependencies:
- axios to 1.8.2 min (note the change to minor min)
- debug to 4.4.0 min
- eslint to 8.57.1 (9.X update will come in with eslint-config-axway v10 soon-ish)
- eslint-plugin-mocha to 10.5.0
- mocha to 11.1.0 ('cause cross-spawn)
- nyc to 17.1.0

2.1.2 - Dependency updates

---

lib/index.js

This PR fixes a bug happening in certain services when not using UPPER case for HTTP methods.
This PR fixes a bug with referencing `debug`, instead of `logger`.

Use UPPERCASE for HTTP methods
